# Starter pipeline
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Pay-As-You-Go(4afcf150-6695-4eb9-a2ee-c28c9859ce18)'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: 'az deployment group create --template-file .\vmdeploywithiis.json --mode complete -g cloud-shell-storage-centralindia'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Pay-As-You-Go(1)(4afcf150-6695-4eb9-a2ee-c28c9859ce18)'
    subscriptionId: '4afcf150-6695-4eb9-a2ee-c28c9859ce18'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'cloud-shell-storage-centralindia'
    location: 'Central India'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://github.com/rajinioff/armvmdeploy/blob/arm-deploy/vmdeploywithiis.json'
    deploymentMode: 'Incremental'
trigger:
- arm-deploy

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
